// AUTO-GENERATED by scripts/gen-image-sizes.mjs — do not edit by hand.
// Maps a /public webp path to the responsive widths generated for it.
// lib/static-image-loader.ts resolves next/image width requests against this.
export const imageSizes: Record<string, number[]> = {
  "/destinations/arugam-bay.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/bentota.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/colombo-airport.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/colombo.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/dambulla.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/ella-nine-arch.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/galle.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/hikkaduwa.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/kandy.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/matara.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/mirissa.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/negombo.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/nuwara-eliya.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/pasikuda.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/sigiriya.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/trincomalee.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/destinations/yala.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/fleet/bicycle.webp": [
    320,
    480,
    640,
    828,
    1080
  ],
  "/fleet/coaster.webp": [
    320,
    480,
    640
  ],
  "/fleet/fit-shuttle.webp": [
    320,
    480,
    640,
    828
  ],
  "/fleet/safari-jeep.webp": [
    320,
    480,
    640
  ],
  "/fleet/scooter.webp": [
    320,
    480,
    640,
    828,
    1080
  ],
  "/fleet/taxi-car.webp": [
    320,
    480
  ],
  "/fleet/taxi-prius.webp": [
    320,
    480,
    640,
    828,
    1080
  ],
  "/fleet/taxi-suv.webp": [
    320,
    480
  ],
  "/fleet/taxi-wagon.webp": [
    320,
    480,
    640,
    828,
    1080
  ],
  "/fleet/tuktuk.webp": [
    320,
    480,
    640
  ],
  "/fleet/van.webp": [
    320,
    480,
    640,
    828,
    1080
  ],
  "/gallery/birds-sunset.webp": [
    320,
    480,
    640
  ],
  "/gallery/boat-mangrove.webp": [
    320,
    480,
    640,
    828
  ],
  "/gallery/buffalo.webp": [
    320
  ],
  "/gallery/crocodiles.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/gallery/deer.webp": [
    320,
    480,
    640
  ],
  "/gallery/scooter-couple.webp": [
    320,
    480,
    640,
    828
  ],
  "/gallery/scooter-group.webp": [
    320,
    480,
    640
  ],
  "/gallery/scooter-park.webp": [
    320,
    480,
    640
  ],
  "/hero/beach.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/hero/elephant.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/hero/fishermen.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/hero/leopard.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/hero/sigiriya.webp": [
    320,
    480,
    640,
    828,
    1080,
    1400
  ],
  "/logos/logo-badge.webp": [
    320,
    480
  ],
  "/logos/logo-mark.webp": [
    320,
    480
  ]
};
