/**
 * Convert every photo in public/ to WebP (smaller, same quality) and generate a
 * tiny blur-placeholder map for next/image blur-up.
 *
 * Run: node scripts/to-webp.mjs
 *
 * - Walks public/** for .jpg/.jpeg/.png, writes a sibling .webp (quality 78).
 * - Skips public/og.jpg (social-share crawlers want a JPEG) and app/ icons.
 * - Emits data/blur.ts: a { "/path.webp": "data:image/webp;base64,…" } map built
 *   from a 16px-wide version of each image, for placeholder="blur".
 * After running, image references in data/*.ts and components use the .webp paths.
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, "public");
const SKIP = new Set([path.join(PUBLIC, "og.jpg")]); // keep og as jpg

function walk(dir) {
  const out = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(jpe?g|png)$/i.test(name)) out.push(full);
  }
  return out;
}

const files = walk(PUBLIC).filter((f) => !SKIP.has(f));
const blur = {};
let converted = 0;
let savedBytes = 0;

for (const src of files) {
  const dest = src.replace(/\.(jpe?g|png)$/i, ".webp");
  const beforeSize = fs.statSync(src).size;

  await sharp(src).rotate().webp({ quality: 78, effort: 5 }).toFile(dest);
  converted++;
  savedBytes += beforeSize - fs.statSync(dest).size;

  // tiny blur placeholder (16px wide webp -> base64)
  const tiny = await sharp(src).rotate().resize({ width: 16 }).webp({ quality: 40 }).toBuffer();
  const publicPath = "/" + path.relative(PUBLIC, dest).split(path.sep).join("/");
  blur[publicPath] = `data:image/webp;base64,${tiny.toString("base64")}`;

  console.log("  ✓", publicPath);
}

// Write the generated blur map
const blurFile = path.join(ROOT, "data", "blur.ts");
const body =
  "// AUTO-GENERATED by scripts/to-webp.mjs — do not edit by hand.\n" +
  "// Maps a /public webp path to a tiny base64 blur placeholder for next/image.\n" +
  "export const blur: Record<string, string> = " +
  JSON.stringify(blur, null, 2) +
  ";\n";
fs.writeFileSync(blurFile, body);

console.log(`\nDone: ${converted} images → webp, blur map with ${Object.keys(blur).length} entries.`);
console.log(`Saved ~${(savedBytes / 1024 / 1024).toFixed(2)} MB vs originals.`);
